title: Susie MacMurray
description: >
  Susie MacMurray is a British artist whose work includes drawing, sculpture and architectural installations.
url: "https://www.susie-macmurray.co.uk"
kramdown:
  input: GFM
include: ["_pages"]
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - LICENSE
  - README.md

collections_dir: collections
collections:
  categories:
    output: true
  essays:
    output: true
    permalink: /published-materials/:name
  sculptures:
    output: true
    permalink: images/:collection/:name
  small-works:
    output: true
    permalink: images/:collection/:name
  drawings:
    output: true
    permalink: images/:collection/:name
  garment-sculptures:
    output: true
    permalink: images/:collection/:name
  site-specific-installations:
    output: true
    permalink: images/:collection/:name
  recent-works:
    output: false

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"
  - scope:
      path: ""
      type: "drawings"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "sculptures"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "site-specific-installations"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "garment-sculptures"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "small-works"
    values:
      layout: "portfolio"
